# Generated by Django 4.0.3 on 2022-04-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postmodel_options_postmodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='rep_link',
            field=models.CharField(default='github.com/blendirrustemi', max_length=100),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blendi_rrustemi.png', null=True, upload_to=''),
        ),
    ]
